-- Student: Svetlana Komarova
-- DBAS32100 Database Management
-- December 5, 2021


--*********************** PART A *********************************

-- *********************************
-- 1.1 Create the tables
-- *********************************
-- 1. Customer Table-------------------------

CREATE TABLE Customer
    (Cust_ID NUMBER  GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1) NOT NULL,
    Cust_First_Name VARCHAR2(20) NOT NULL,
    Cust_Last_Name VARCHAR2(40) NOT NULL,
    Cust_Phone_Number VARCHAR(25) NOT NULL,
    Cust_Birthdate DATE,
    Driver_License_Number NUMBER, 
    Cust_Status VARCHAR2(20),
    CONSTRAINT Cust_ID_pk 
        PRIMARY KEY(Cust_ID));
    
-- 2. Movie Category Table-------------------------

CREATE TABLE Movie_Category 
    (Cat_ID NUMBER  GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    Cat_Name VARCHAR2(25) NOT NULL,
    CONSTRAINT Cat_ID_pk 
        PRIMARY KEY(Cat_ID));

-- 3. DVD Table-------------------------

CREATE TABLE DVD
    (Tape_ID NUMBER  GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    Title VARCHAR2(50) NOT NULL,
    Movie_Year NUMBER,
    Rent_Cost NUMBER(7,2),
    Cat_ID NUMBER NOT NULL,
    Rented_Out VARCHAR2(3),
    Rating VARCHAR2(3),
    Action_On_Return VARCHAR2(25),
    CONSTRAINT Tape_ID_pk 
        PRIMARY KEY(Tape_ID),
    CONSTRAINT Cat_ID_fk 
        FOREIGN KEY (Cat_ID) 
        REFERENCES Movie_Category(Cat_ID)
        ON DELETE CASCADE);
     
-- 4. Rental Table-------------------------

CREATE TABLE Rental
    (Rental_ID NUMBER  GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1) NOT NULL,
    Rental_Date DATE NOT NULL,
    Cust_ID NUMBER NOT NULL,
    Tape_ID NUMBER NOT NULL,
    CONSTRAINT Rental_ID_pk 
        PRIMARY KEY(Rental_ID),
    CONSTRAINT Cust_ID_fk 
        FOREIGN KEY (Cust_ID) 
        REFERENCES Customer(Cust_ID)
        ON DELETE CASCADE,
    CONSTRAINT Tape_ID_fk 
        FOREIGN KEY (Tape_ID) 
        REFERENCES DVD(Tape_ID)
        ON DELETE CASCADE);

--********************************* 
--1.2 Populate each of the tables with data given in the excel file 
--*********************************

-- 1. ------------ Customer TABLE -------------------
INSERT INTO Customer (Cust_First_Name, Cust_Last_Name, Cust_Phone_Number, Cust_Birthdate, Driver_License_Number, Cust_Status) 
        VALUES ('Edward', 'Vongsaphay', '(905) 555-8932', TO_DATE('1/1/1990', 'mm/dd/yyyy'), 537597397, 'Active');
INSERT INTO Customer (Cust_First_Name, Cust_Last_Name, Cust_Phone_Number, Cust_Birthdate, Driver_License_Number, Cust_Status) 
        VALUES ('Fiona', 'Esposito', '(905) 345-3920', TO_DATE('3/28/1955', 'mm/dd/yyyy'), 232323290, 'Active');
INSERT INTO Customer (Cust_First_Name, Cust_Last_Name, Cust_Phone_Number, Cust_Birthdate, Driver_License_Number, Cust_Status) 
        VALUES ('Graeme', 'Sands', '(416) 849-5391', TO_DATE('11/30/1973', 'mm/dd/yyyy'), 492830981, 'Amount Owing');
INSERT INTO Customer (Cust_First_Name, Cust_Last_Name, Cust_Phone_Number, Cust_Birthdate, Driver_License_Number, Cust_Status) 
        VALUES ('Margeret', 'Armstrong', '(905) 745-7342', TO_DATE('6/19/1968', 'mm/dd/yyyy'), 987654336, 'Suspended');
INSERT INTO Customer (Cust_First_Name, Cust_Last_Name, Cust_Phone_Number, Cust_Birthdate, Driver_License_Number, Cust_Status) 
        VALUES ('Michael', 'McGuinty', '(905) 648-3246', TO_DATE('3/30/1984', 'mm/dd/yyyy'), 345678998, 'Active');
INSERT INTO Customer (Cust_First_Name, Cust_Last_Name, Cust_Phone_Number, Cust_Birthdate, Driver_License_Number, Cust_Status) 
        VALUES ('Phil', 'Charest', '(416) 371-3979', TO_DATE('12/10/1980', 'mm/dd/yyyy'), 604604047, 'Suspended');
INSERT INTO Customer (Cust_First_Name, Cust_Last_Name,Cust_Phone_Number, Cust_Birthdate) 
        VALUES ('Paula', 'Chow', '(416) 635-5555', TO_DATE('10/12/1979', 'mm/dd/yyyy'));


-- 2. ------------ Movie_Category TABLE -------------------
INSERT INTO Movie_Category (Cat_Name) VALUES ('Action/Adventure');
INSERT INTO Movie_Category (Cat_Name) VALUES ('Biography');
INSERT INTO Movie_Category (Cat_Name) VALUES ('Children');
INSERT INTO Movie_Category (Cat_Name) VALUES ('Comedy');
INSERT INTO Movie_Category (Cat_Name) VALUES ('Drama');
INSERT INTO Movie_Category (Cat_Name) VALUES ('Horror');
INSERT INTO Movie_Category (Cat_Name) VALUES ('Musical');
INSERT INTO Movie_Category (Cat_Name) VALUES ('Science Fiction');


-- 3. ------------ DVD TABLE -------------------
INSERT INTO DVD (Title, Movie_Year, Rent_Cost, Cat_ID, Rented_Out, Rating, Action_On_Return) 
        VALUES ('Elizabeth: The Golden Age', 2008, 5.29, 5, 'Yes', 'PG', 'Return to Shelf');
INSERT INTO DVD (Title, Movie_Year, Rent_Cost, Cat_ID, Rented_Out, Rating, Action_On_Return) 
        VALUES ('The Bourne Ultimatum', 2006, 3.99, 1, 'No', 'PG', 'Sell');
INSERT INTO DVD (Title, Movie_Year, Rent_Cost, Cat_ID, Rented_Out, Rating, Action_On_Return) 
        VALUES ('Shrek 2', 2004, 3.99, 3, 'No', '3', 'Return to Shelf');
INSERT INTO DVD (Title, Movie_Year, Rent_Cost, Cat_ID, Rented_Out, Rating, Action_On_Return) 
        VALUES ('Ace Ventura, Pet Detective', 1994, 3.99, 4, 'No', '14A', 'Sell');
INSERT INTO DVD (Title, Movie_Year, Rent_Cost, Cat_ID, Rented_Out, Rating, Action_On_Return) 
        VALUES ('Hairspray', 2007, 5.29, 7, 'No', 'PG', 'Sell');
INSERT INTO DVD (Title, Movie_Year, Rent_Cost, Cat_ID, Rented_Out, Rating, Action_On_Return) 
        VALUES ('A Charlie Brown Christmas', 2000, 3.99, 3, 'No', 'G', 'Return to Shelf');
INSERT INTO DVD (Title, Movie_Year, Rent_Cost, Cat_ID, Rented_Out, Rating, Action_On_Return) 
        VALUES ('Leonard Cohen: I' || '''' || 'm Your Man', 2006, 3.99, 2, 'Yes', 'PG', 'Return to Shelf');
INSERT INTO DVD (Title, Movie_Year, Rent_Cost, Cat_ID, Rented_Out, Rating, Action_On_Return) 
        VALUES ('Nightmare on Elm Street', 1999, 3.99, 6, 'Yes', 'R', 'Return to Shelf');
INSERT INTO DVD (Title, Movie_Year, Rent_Cost, Cat_ID, Rented_Out, Rating, Action_On_Return) 
        VALUES ('Star Trek: Nemesis', 2005, 3.99, 8, 'Yes', 'PG', 'Return to Shelf');
INSERT INTO DVD (Title, Movie_Year, Rent_Cost, Cat_ID, Rented_Out, Rating, Action_On_Return) 
        VALUES ('The King' || '''' || 's Speech', 2010, 5.29, 5, 'Yes', 'R', 'Return to Shelf');
INSERT INTO DVD (Title, Movie_Year, Rent_Cost, Cat_ID, Rented_Out, Rating, Action_On_Return) 
        VALUES ('True Grit', 2010, 5.29, 1, 'Yes', 'PG', 'Return to Shelf');  

-- 3. ------------ Rental TABLE -------------------
INSERT INTO Rental (Rental_Date, Cust_ID, Tape_ID) VALUES (TO_DATE('12/2/2011', 'mm/dd/yyyy'), 101, 10);
INSERT INTO Rental (Rental_Date, Cust_ID, Tape_ID) VALUES (TO_DATE('12/2/2011', 'mm/dd/yyyy'), 101, 3);
INSERT INTO Rental (Rental_Date, Cust_ID, Tape_ID) VALUES (TO_DATE('12/2/2011', 'mm/dd/yyyy'), 104, 6);
INSERT INTO Rental (Rental_Date, Cust_ID, Tape_ID) VALUES (TO_DATE('12/7/2011', 'mm/dd/yyyy'), 106, 1);
INSERT INTO Rental (Rental_Date, Cust_ID, Tape_ID) VALUES (TO_DATE('12/7/2011', 'mm/dd/yyyy'), 102, 7);
INSERT INTO Rental (Rental_Date, Cust_ID, Tape_ID) VALUES (TO_DATE('12/7/2011', 'mm/dd/yyyy'), 102, 9);

/
COMMIT;     

-- *********************************
-- 2. Create PL/SQL scripts to support following operations for each table.    
    --	Insert Data
    --	Update Data
    --	Delete Data 
-- *********************************

---------------INSERT-------------------------

-- 1. ------------ Customer TABLE -------------------
CREATE OR REPLACE PROCEDURE insert_Customer
(
        p_First_Name IN Customer.Cust_First_Name%TYPE,
        p_Last_Name IN Customer.Cust_Last_Name%TYPE,
        p_Phone_Number IN Customer.Cust_Phone_Number%TYPE,
        p_Birthdate IN Customer.Cust_Birthdate%TYPE,
        p_Driver_License IN Customer.Driver_License_Number%TYPE,
        p_Status IN Customer.Cust_Status%TYPE
)
IS
BEGIN
        INSERT INTO Customer (Cust_First_Name, Cust_Last_Name, Cust_Phone_Number, Cust_Birthdate, Driver_License_Number, Cust_Status) 
            VALUES (p_First_Name, p_Last_Name, p_Phone_Number, p_Birthdate, p_Driver_License,  p_Status);
      
COMMIT;
END;

-- ask user for input
-- execute insert_Customer
ACCEPT p_first_name PROMPT 'Enter Customer Fisrt Name: '
ACCEPT p_last_name PROMPT 'Enter Customer Last Name: '
ACCEPT p_phone_number PROMPT 'Enter Customer Phone Number: '
ACCEPT p_birthdate PROMPT 'Enter Customer Date of Birth in "mm/dd/yyy" format: '
ACCEPT p_dl PROMPT 'Enter Customer Driver License: '
ACCEPT p_status PROMPT 'Enter Customer Status: '

EXEC insert_Customer('&p_first_name', '&p_last_name', '&p_phone_number', TO_DATE('&p_birthdate', 'mm/dd/yyyy'), &p_dl,  '&p_status');

--SELECT * FROM Customer;
    
-- 2. ------------ Movie_Category TABLE -------------------
CREATE OR REPLACE PROCEDURE insert_Movie_Category
(
        p_Cat_Name IN Movie_Category.Cat_Name%TYPE
)
IS
BEGIN
        INSERT INTO Movie_Category (Cat_Name) VALUES (p_Cat_Name);
        
COMMIT;
END;

-- ask user for input
-- execute insert_Movie_Category
ACCEPT p_category PROMPT 'Enter Movie Category: '
EXEC insert_Movie_Category('&p_category');

--SELECT * FROM Movie_Category;

-- 3. ------------ DVD TABLE -------------------
CREATE OR REPLACE PROCEDURE insert_DVD
(
        p_Title IN DVD.Title%TYPE,
        p_Movie_Year IN DVD.Movie_Year%TYPE,
        p_Rent_Cost IN DVD.Rent_Cost%TYPE,
        p_Cat_ID IN DVD.Cat_ID%TYPE,
        p_Rented_Out IN DVD.Rented_Out%TYPE,
        p_Rating IN DVD.Rating%TYPE,
        p_Action_On_Return IN DVD.Action_On_Return%TYPE
)
IS
BEGIN
        INSERT INTO DVD (Title, Movie_Year, Rent_Cost, Cat_ID, Rented_Out, Rating, Action_On_Return) 
            VALUES (p_Title, p_Movie_Year, p_Rent_Cost, p_Cat_ID, p_Rented_Out, p_Rating, p_Action_On_Return);
        
COMMIT;
END;

-- ask user for input
-- execute insert_DVD
ACCEPT p_title PROMPT 'Enter Movie Title: '
ACCEPT p_year PROMPT 'Enter Movie Year: '
ACCEPT p_cost PROMPT 'Enter Rent Cost: '
ACCEPT p_cat_id PROMPT 'Enter Category ID: '
ACCEPT p_rent_out PROMPT 'Enter Rented Out (yes/no): '
ACCEPT p_rating PROMPT 'Enter Rating: '
ACCEPT p_action PROMPT 'Enter Action: '

EXEC insert_DVD('&p_title', &p_year, &p_cost, &p_cat_id, '&p_rent_out',  '&p_rating', '&p_action');

--SELECT * FROM DVD;

-- 4. ------------ Rental TABLE -------------------
CREATE OR REPLACE PROCEDURE insert_Rental
(     
        p_Rental_Date IN Rental.Rental_Date%TYPE,
        p_Cust_ID IN Rental.Cust_ID%TYPE,
        p_Tape_ID IN Rental.Tape_ID%TYPE
)
IS
BEGIN
        INSERT INTO Rental (Rental_Date, Cust_ID, Tape_ID) VALUES (p_Rental_Date, p_Cust_ID, p_Tape_ID);
        
COMMIT;
END;

-- ask user for input
-- execute insert_Rental
ACCEPT p_date PROMPT 'Enter Rental Date in "mm/dd/yyy" format: '
ACCEPT p_cust_id PROMPT 'Enter Customer ID: '
ACCEPT p_tape_id PROMPT 'Enter Tape ID: '

EXEC insert_Rental(TO_DATE('&p_date', 'mm/dd/yyyy'), &p_cust_id, &p_tape_id);

--SELECT * FROM Rental;

---------------UPDATE-------------------------

-- 1. ------------ Customer TABLE -------------------
CREATE OR REPLACE PROCEDURE update_Customer
(
        p_Cust_ID IN Customer.Cust_ID%TYPE,
        p_Driver_License IN Customer.Driver_License_Number%TYPE,
        p_Status IN Customer.Cust_Status%TYPE
)
IS
BEGIN	
    UPDATE Customer
    SET  Driver_License_Number = p_Driver_License, Cust_Status = p_Status
    WHERE Cust_ID = p_Cust_ID;
    
COMMIT;
END;

-- ask user for input
-- execute update_Customer
ACCEPT p_id PROMPT 'Enter Customer ID to update:'
ACCEPT p_new_dl PROMPT 'Enter Driver License Number:'
ACCEPT p_new_status PROMPT 'Enter Customer Status:'

EXEC update_Customer(&p_id, &p_new_dl, '&p_new_status');

--SELECT * FROM Customer;

-- 2. ------------ Movie_Category TABLE -------------------
CREATE OR REPLACE PROCEDURE update_Movie_Category
(
         p_Cat_ID IN Movie_Category.Cat_ID%TYPE,
        p_Cat_Name IN Movie_Category.Cat_Name%TYPE
)
IS
BEGIN	
    UPDATE Movie_Category
    SET  Cat_Name = p_Cat_Name
    WHERE Cat_ID = p_Cat_ID;
    
COMMIT;
END;

-- ask user for input
-- execute update_Movie_Category
ACCEPT p_id PROMPT 'Enter Movie Category ID to update:'
ACCEPT p_new_category PROMPT 'Enter Movie Category:'
EXEC update_Movie_Category(&p_id, '&p_new_category');

--SELECT * FROM Movie_Category;

-- 3. ------------ DVD TABLE -------------------
CREATE OR REPLACE PROCEDURE update_DVD
(
        p_DVD_ID IN DVD.Tape_ID%TYPE,
        p_New_Cost IN DVD.Rent_Cost%TYPE      
)
IS
BEGIN	
    UPDATE DVD
    SET  Rent_Cost = p_New_Cost
    WHERE Tape_ID = p_DVD_ID;
    
COMMIT;
END;

-- ask user for input
-- execute update_DVD
ACCEPT p_dvd_id PROMPT 'Enter DVD id to update the price:'
ACCEPT p_new_price PROMPT 'Enter price for DVD:'
EXEC update_DVD(&p_dvd_id, &p_new_price);

--SELECT * FROM DVD;

-- 4. ------------ Rental TABLE -------------------
CREATE OR REPLACE PROCEDURE update_Rental 
(
        p_Rental_ID IN Rental.Rental_ID%TYPE,
        p_Rental_Date IN Rental.Rental_Date%TYPE
)
IS
BEGIN	
    UPDATE Rental
    SET  Rental_Date = p_Rental_Date
    WHERE Rental_ID = p_Rental_ID;

COMMIT;
END;

-- ask user for input
-- execute update_Rental 
ACCEPT p_id PROMPT 'Enter Rental ID to update:'
ACCEPT p_new_date PROMPT 'Enter Rental Date (mm/dd/yyy):'
EXEC update_Rental(&p_id, TO_DATE('&p_new_date', 'mm/dd/yyyy'));

--SELECT * FROM Rental;

---------------DELETE-------------------------

-- 1. ------------ Customer TABLE --------------------
CREATE OR REPLACE PROCEDURE delete_Customer
(
        p_Cust_ID IN Customer.Cust_ID%TYPE
)
IS
BEGIN
    DELETE
    FROM Customer
    WHERE Cust_ID = p_Cust_ID;
    
COMMIT;
END;

-- ask user for input
-- execute delete_Customer
ACCEPT p_id PROMPT 'Enter Customer ID to delete:'
EXEC delete_Customer(&p_id);

--SELECT * FROM Customer;

-- 2. ------------ Movie_Category TABLE -------------------
CREATE OR REPLACE PROCEDURE delete_Movie_Category
(
        p_Cat_Name IN Movie_Category.Cat_Name%TYPE
)
IS
BEGIN
    DELETE
    FROM Movie_Category
    WHERE Cat_Name = p_Cat_Name;
    
COMMIT;
END;

-- ask user for input
-- execute delete_Movie_Category
ACCEPT p_category PROMPT 'Enter Movie Category to delete:'
EXEC delete_Movie_Category(UPPER('&p_category'));

--SELECT * FROM Movie_Category;

-- 3. ------------ DVD TABLE -------------------
CREATE OR REPLACE PROCEDURE delete_DVD
(
        p_Tape_Id IN DVD.Tape_ID%TYPE
)
IS
BEGIN
    DELETE
    FROM DVD
    WHERE Tape_ID = p_Tape_Id;
    
COMMIT;
END;

-- ask user for input
-- execute delete_DVD
ACCEPT p_tape_id PROMPT 'Enter Tape ID to delete:'
EXEC delete_DVD(&p_tape_id);

--SELECT * FROM DVD;

-- 4. ------------ Rental TABLE -------------------
CREATE OR REPLACE PROCEDURE delete_Rental
(
        p_Rental_ID IN Rental.Rental_ID%TYPE
)
IS
BEGIN
    DELETE
    FROM Rental
    WHERE Rental_ID = p_Rental_ID;
    
COMMIT;
END;

-- ask user for input
-- execute delete_Rental
ACCEPT p_id PROMPT 'Enter Rental ID to delete:'
EXEC delete_Rental(&p_id);

--SELECT * FROM Rental;

-- *********************************
-- Write PL/SQL Scripts for all following questions:
-- *********************************

--a.	Which movie(s) is/are available right now to rent out?

SET SERVEROUTPUT ON;

DECLARE
         -- cursor
        CURSOR cr IS SELECT  Title, Movie_Year
                                                FROM DVD
                                                WHERE UPPER(Rented_Out) = 'NO';
BEGIN
        FOR v_rec IN cr
            LOOP
                DBMS_OUTPUT.PUT_LINE( v_rec.Title || ', Year ' || v_rec.Movie_Year);
            END LOOP;
END;

------------------------------------   
--b.	Show the movies which has least renting cost and highest renting cost?

SET SERVEROUTPUT ON;

DECLARE
         -- cursor
        CURSOR cr IS SELECT Title, Rent_Cost
                                        FROM 
                                                (SELECT Title, Rent_Cost, 
                                                        MIN(Rent_Cost) OVER () AS Lowest_list_price,
                                                        MAX(Rent_Cost) OVER () AS Highest_list_price
                                                FROM DVD)
                                        WHERE Rent_Cost = Lowest_list_price OR Rent_Cost = Highest_list_price
                                        ORDER BY Rent_Cost, Title;
BEGIN
        FOR v_rec IN cr
            LOOP
               DBMS_OUTPUT.PUT_LINE( v_rec.Title || ': $' || v_rec.Rent_Cost);
            END LOOP;
END;

------------------------------------
--c.	Show all the detail of a customer and the movies he/she is renting.

SET SERVEROUTPUT ON;

DECLARE
         -- cursor
        CURSOR cr IS SELECT c.Cust_First_Name firstname, c.Cust_Last_Name lastname, c.Cust_Phone_Number phone, 
                                                c.Cust_Birthdate bd, NVL(c.Driver_License_Number, 0) dln, NVL(c.Cust_Status, 'n/a') status,  
                                                d.Title title, d.Movie_Year m_year, d.Rent_Cost r_cost, d.Rating rating
                                        FROM Customer c INNER JOIN Rental r
                                        ON c.Cust_ID = r.Cust_ID
                                        INNER JOIN DVD d
                                        ON r.Tape_ID = d.Tape_ID
                                        WHERE UPPER(d.Rented_Out) = 'YES'
                                        ORDER BY c.Cust_Last_Name;
BEGIN
        FOR v_rec IN cr
            LOOP
               DBMS_OUTPUT.PUT_LINE (v_rec.lastname || ', ' || v_rec.firstname || ' ' || v_rec.phone || ' ' ||  v_rec.bd || ' ' ||  v_rec.dln || ' ' ||
                                                           v_rec.status || ' ' || v_rec.m_year || ' ' || v_rec.rating || ' ' || v_rec.title || ' ' || v_rec.r_cost);
            END LOOP;
END;

------------------------------------
--d.	Show the names of the customers and the number of movies rented by him.

SET SERVEROUTPUT ON;

DECLARE
         -- cursor
        CURSOR cr IS SELECT c.Cust_First_Name firstname, c.Cust_Last_Name lastname, COUNT(r.Rental_ID) number_of_movies           
                                    FROM Customer c INNER JOIN Rental r
                                    ON c.Cust_ID = r.Cust_ID
                                    GROUP BY c.Cust_First_Name, c.Cust_Last_Name
                                    ORDER BY c.Cust_Last_Name, c.Cust_First_Name;
BEGIN
        FOR v_rec IN cr
            LOOP
               DBMS_OUTPUT.PUT_LINE( v_rec.lastname || ', ' || v_rec.firstname || ' rented out ' || v_rec.number_of_movies || ' movie/movies');
            END LOOP;
END;

-- *********************************
--4. Make sure who so ever is using your database and manipulating data, 
-- (using triggers) your database should keep log of insert / update / delete operation 
-- (and data changed) and should convert to uppercase before entering it. 
-- *********************************

---------------LOG TABLE to keep log of operations on all tables------------------------

CREATE TABLE user_log(
    table_name VARCHAR2(20),
    user_id VARCHAR2(30),
    action VARCHAR2(1),
    log_date_time TIMESTAMP);
    

---------------TRIGGERS to write the data to LOG TABLE-------------------------

-- 1. ------------ on Customer TABLE --------------------
CREATE OR REPLACE TRIGGER customer_user_trg
AFTER INSERT OR UPDATE OR DELETE
ON Customer
FOR EACH ROW
DECLARE
        v_table_name VARCHAR2(20) := 'Customer';
BEGIN
   CASE
    WHEN INSERTING THEN
        INSERT INTO user_log(table_name, user_id, action, log_date_time) VALUES(v_table_name, USER, 'I',SYSTIMESTAMP);
    WHEN UPDATING THEN
        INSERT INTO user_log(table_name, user_id, action, log_date_time) VALUES(v_table_name, USER, 'U', SYSTIMESTAMP);
    WHEN DELETING THEN
        INSERT INTO user_log(table_name, user_id, action, log_date_time) VALUES(v_table_name, USER, 'D', SYSTIMESTAMP);
    END CASE;
END;
  
-- 2. ------------on Rental TABLE -------------------
CREATE OR REPLACE TRIGGER rental_user_trg
AFTER INSERT OR UPDATE OR DELETE
ON Rental
FOR EACH ROW
DECLARE
        v_table_name VARCHAR2(20) := 'Rental';
BEGIN
   CASE
    WHEN INSERTING THEN
        INSERT INTO user_log(table_name, user_id, action, log_date_time) VALUES(v_table_name, USER, 'I', SYSTIMESTAMP);
    WHEN UPDATING THEN
        INSERT INTO user_log(table_name, user_id, action, log_date_time) VALUES(v_table_name, USER, 'U', SYSTIMESTAMP);
    WHEN DELETING THEN
        INSERT INTO user_log(table_name, user_id, action, log_date_time) VALUES(v_table_name, USER, 'D', SYSTIMESTAMP);
    END CASE;
END;

-- 3. ------------on DVD TABLE -------------------
CREATE OR REPLACE TRIGGER DVD_user_trg
AFTER INSERT OR UPDATE OR DELETE
ON DVD
FOR EACH ROW
DECLARE
        v_table_name VARCHAR2(20) := 'DVD';
BEGIN
   CASE
    WHEN INSERTING THEN
        INSERT INTO user_log(table_name, user_id, action, log_date_time) VALUES(v_table_name, USER, 'I', SYSTIMESTAMP);
    WHEN UPDATING THEN
        INSERT INTO user_log(table_name, user_id, action, log_date_time) VALUES(v_table_name, USER, 'U', SYSTIMESTAMP);
    WHEN DELETING THEN
        INSERT INTO user_log(table_name, user_id, action, log_date_time) VALUES(v_table_name, USER, 'D', SYSTIMESTAMP);
    END CASE;
END;

-- 4. ------------on Movie_Category TABLE -------------------
CREATE OR REPLACE TRIGGER movie_user_trg
AFTER INSERT OR UPDATE OR DELETE
ON Movie_Category
FOR EACH ROW
DECLARE
        v_table_name VARCHAR2(20) := 'Movie_Category';
BEGIN
   CASE
    WHEN INSERTING THEN
        INSERT INTO user_log(table_name, user_id, action, log_date_time) VALUES(v_table_name, USER, 'I', SYSTIMESTAMP );
    WHEN UPDATING THEN
        INSERT INTO user_log(table_name, user_id, action, log_date_time) VALUES(v_table_name, USER, 'U', SYSTIMESTAMP );
    WHEN DELETING THEN
        INSERT INTO user_log(table_name, user_id, action, log_date_time) VALUES(v_table_name, USER, 'D', SYSTIMESTAMP );
    END CASE;
END;


---------------TRIGGERS to convert  the data to uppercase before insert/update-------------------------

-- 1. ------------ on Customer TABLE --------------------
CREATE OR REPLACE TRIGGER upper_customer_trg
BEFORE INSERT OR UPDATE 
ON Customer
FOR EACH ROW
BEGIN
    :NEW.Cust_FIRST_NAME := UPPER(:NEW.Cust_FIRST_NAME);
    :NEW.Cust_LAST_NAME := UPPER(:NEW.Cust_LAST_NAME);
    :NEW.Cust_Status := UPPER(:NEW.Cust_Status);
END;

-- 2. ------------on Movie_Category TABLE -------------------
CREATE OR REPLACE TRIGGER upper_movie_category_trg
BEFORE INSERT OR UPDATE 
ON Movie_Category
FOR EACH ROW
BEGIN
    :NEW.Cat_Name := UPPER(:NEW.Cat_Name);
END;  

-- 3.------------on DVD TABLE -------------------
CREATE OR REPLACE TRIGGER upper_DVD_trg
BEFORE INSERT OR UPDATE 
ON DVD
FOR EACH ROW
BEGIN
    :NEW.Title := UPPER(:NEW.Title);
    :NEW.Rented_Out := UPPER(:NEW.Rented_Out);
    :NEW.Rating := UPPER(:NEW.Rating);
    :NEW.Action_On_Return := UPPER(:NEW.Action_On_Return);
END;

-- *********************************
--5. Drop all the tables created in the beginning of the Part A.
-- *********************************

DROP TABLE Rental;
DROP TABLE DVD;
DROP TABLE Customer;
DROP TABLE Movie_Category;

--*********************** PART B *********************************

-- *********************************
-- Create a Star Schema out of DVD table, to find out 
-- the total amount of cost for each category, each year and Rating. 
-- *********************************

-- 1. ------------Fact Table -------------------
CREATE TABLE Fact_Rent
    (C_ID NUMBER,
    P_ID NUMBER,
    R_ID NUMBER,
    Rent_Cost NUMBER(7,2));
    
-- 2. ------------Category Dimension Table -------------------
 
CREATE TABLE Dim_Category
    (C_ID NUMBER,
    Cat_ID NUMBER,
    Cat_Name VARCHAR2(25));
    
-- 3. ------------Period Dimension Table -------------------
        
CREATE TABLE Dim_Period
    (P_ID NUMBER,
    P_Year NUMBER);

-- 3. ------------Rating Dimension Table -------------------
    
CREATE TABLE Dim_Rating
    (R_ID NUMBER,
    Tape_ID NUMBER,
    Rating VARCHAR2(3));
    
-------------------------------------------

-- Create sequence
CREATE SEQUENCE Dim_ID;

-- *********************************
-- Populate each of the tables (fact and dimension) with appropriate values from the DVD table. 
-- Use sequence as a source of  surrogate keys for the dimension tables and 
-- use cursor to populate the values in the fact table without losing any information. 
-- *********************************

INSERT INTO Dim_Category
SELECT Dim_ID.NEXTVAL, Cat_ID, Cat_Name
FROM Movie_Category;

--SELECT * FROM Dim_Category;
------------------------------------------------

INSERT INTO Dim_Period
SELECT Dim_ID.NEXTVAL, Yr
FROM (SELECT DISTINCT  Movie_Year AS Yr
            FROM DVD);
   
--SELECT * FROM Dim_Period;
------------------------------------------------

INSERT INTO Dim_Rating
SELECT Dim_ID.NEXTVAL, Tape_ID, Rating
FROM DVD;

--SELECT * FROM Dim_Rating
------------------------------------------------

DECLARE 
        TYPE Arr_Rent IS TABLE OF Fact_Rent%ROWTYPE;
        Rent Arr_Rent;
        
        CURSOR cr IS SELECT C_ID, P_ID, R_ID, SUM(Rent_Cost)
                                FROM DVD d INNER JOIN Dim_Category c
                                ON d.Cat_ID = c.Cat_ID
                                INNER JOIN Dim_Rating r
                                ON d.Tape_ID = r.Tape_ID
                                INNER JOIN Dim_Period p
                                ON p.P_Year =  d.Movie_Year
                                GROUP BY C_ID, P_ID, R_ID;
BEGIN
        OPEN cr;
                FETCH cr BULK COLLECT INTO Rent;
        CLOSE cr;
        
        FOR i IN 1..Rent.LAST LOOP
            IF Rent(i).Rent_Cost IS NULL THEN
                Rent(i).Rent_Cost :=0;
            END IF;
        END LOOP;
    FORALL i IN 1..Rent.LAST
        INSERT INTO Fact_Rent VALUES (Rent(i).C_ID,
                                                                Rent(i).P_ID,
                                                                Rent(i).R_ID,
                                                                Rent(i).Rent_Cost);
END;
/
COMMIT;                               

--SELECT * FROM Fact_Rent;
